"use strict";
let fname;
fname = "kabiraj";
fname = 12345;
//fname=true;
console.log("Hello ", fname);
console.log("Hello World");
console.log("New Change");
console.log("Another New Change");
console.log(typeof (fname));
